/* Populate database with sample data. */

 INSERT INTO animals VALUES (1, 'Agumon', '2020-02-03', 0, true, 10.23);
 INSERT INTO animals VALUES (2, 'Gabumon', '2018-11-15', 2, true, 8);
 INSERT INTO animals VALUES (3, 'Pikachu', '2021-01-7', 1, false, 15.04);
 INSERT INTO animals VALUES (4, 'Devimon', '2017-05-12', 5, true, 11);
 INSERT INTO animals VALUES (5, 'Charmander', '2020-02-08', 0, false, -11);
 INSERT INTO animals VALUES (6, 'Plantmon', '2021-11-15', 2, true, -5.7);
 INSERT INTO animals VALUES (7, 'Squirtle', '1993-04-02', 3, false, -12.13);
 INSERT INTO animals VALUES (8, 'Angemon', '2005-06-12', 1, true, -45);
 INSERT INTO animals VALUES (9, 'Boarmon', '2005-06-07', 7, true, 20.4);
 INSERT INTO animals VALUES (10, 'Blossom', '1998-10-13', 3, true, 17);
 INSERT INTO animals VALUES (11, 'Ditto', '2022-05-14', 4, true, 22);

 --Owners table

INSERT INTO owners (full_name, age) VALUES ('Sam Smith' , 34);
INSERT INTO owners (full_name, age) VALUES ('Jennifer Orwell' , 19);
INSERT INTO owners (full_name, age) VALUES ('Bob' , 45);
INSERT INTO owners (full_name, age) VALUES ('Melody Pond ' , 77);
INSERT INTO owners (full_name, age) VALUES ('Dean Winchester' , 14);
INSERT INTO owners (full_name, age) VALUES ('Jodie Whittaker' , 38);

/*
** species table
*/

INSERT INTO species (name) VALUES ('Pokemon');
INSERT INTO species (name) VALUES ('Digimon');

-- modify animals table with species_id

UPDATE animals SET species_id = (SELECT id FROM species WHERE NAME = 'Digimon') WHERE NAME LIKE '%mon';
UPDATE animals SET species_id = (SELECT id FROM species WHERE NAME = 'Pokemon') WHERE NAME NOT LIKE '%mon';

-- owner_id

UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name  = 'Sam Smith') WHERE name IN('Agumon');
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name  = 'Jennifer Orwell') WHERE name IN('Gabumon' , 'Pikachu');
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name  = 'Bob') WHERE name IN('Devimon', 'Plantmon');
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name  = 'Melody Pond ') WHERE name IN('Charmander', 'Squirtle', 'Blossom');
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name  = 'Dean Winchester') WHERE name IN('Angemon' , 'Boarmon');


--vets table

INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('William Tatcher' , 45 , '2000-04-23');
INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Maisy Smith' , 26 , '2019-01-17');
INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Stephanie Mendez' , 64 , '1981-05-04');
INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Jack Harkness' , 38 , '2008-06-08');


-- Specialties table

INSERT INTO specializations (SPECIES_ID, VETS_ID) SELECT SPECIES.ID, VETS.ID FROM SPECIES INNER JOIN VETS ON SPECIES.NAME = 'Pokemon' AND VETS.NAME = 'William Tatcher';
INSERT INTO specializations (SPECIES_ID, VETS_ID) SELECT SPECIES.ID, VETS.ID FROM SPECIES INNER JOIN VETS ON SPECIES.NAME In('Pokemon', 'Digimon') AND VETS.NAME = 'Stephanie Mendez';
INSERT INTO specializations (SPECIES_ID, VETS_ID) SELECT SPECIES.ID, VETS.ID FROM SPECIES INNER JOIN VETS ON SPECIES.NAME = 'Digimon' AND VETS.NAME = 'Jack Harkness';


-- Visits table

INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-05-24' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Agumon' AND VETS.NAME = 'William Tatcher';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-07-22' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Agumon' AND VETS.NAME = 'Stephanie Mendez';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2021-02-02' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Gabumon' AND VETS.NAME = 'Jack Harkness';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-01-05' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Pikachu' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-03-08' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Pikachu' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-05-14' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Pikachu' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2021-05-04' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Devimon' AND VETS.NAME = 'Stephanie Mendez';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2021-02-24' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Charmander' AND VETS.NAME = 'Jack Harkness';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2019-12-21' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Plantmon' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-08-10' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Plantmon' AND VETS.NAME = 'William Tatcher';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2021-04-07' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Plantmon' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2019-09-29' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Squirtle' AND VETS.NAME = 'Stephanie Mendez';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-10-03' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Angemon' AND VETS.NAME = 'Jack Harkness';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-11-04' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Angemon' AND VETS.NAME = 'Jack Harkness';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2019-01-24' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Boarmon' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2019-05-15' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Boarmon' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-02-27' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Boarmon' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-08-03' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Boarmon' AND VETS.NAME = 'Maisy Smith';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2020-05-24' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Blossom' AND VETS.NAME = 'Stephanie Mendez';
INSERT INTO VISITS (ANIMALS_ID, VETS_ID, VISIT_DATE) SELECT ANIMALS.ID, VETS.ID , '2021-01-11' FROM ANIMALS INNER JOIN VETS ON ANIMALS.NAME = 'Blossom' AND VETS.NAME = 'William Tatcher';
